### ISSUE TITLE
create a list of non-existing (but required) icons

### ISSUE THREAD

**Issue by mvibhakar** [mvibhakar/idylworld#5]
after you implement icons that already exist, make a list of titles that still don't have icons. please post this list in the slack `idylworld` channel.

**Comment by tianavibhakar** [comment]
list of icons needed

**community**
become an influencer
perform arts
pray at community temple

**connected**
easy access to booming economy
easy access to malls and movie theaters

**abundant**
fauna

**bungalow**
blend physical & digital
